### ISSUE TITLE
Leucos : Design Navbar

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Leucos#1]
## Task
- Design a navbar for the website 
- Make it responsive for all devices 
- Add a hamburger menu icon for the nav list items when it's responsive 
- Make a small animation on the hamburger menu icon when clicked 

Reference : https://dribbble.com/shots/15752752-Chat-App-Landing-Page ( Try to make it similar to this navbar )

**Comment by IEdiong** [comment]
Hello 👋 @soujo, can I start working on this?

**Comment by soujo** [comment]
Yes , you can start working on this

**Comment by soujo** [comment]
Any updates ? @IEdiong

**Comment by IEdiong** [comment]
Hi @soujo, I'm currently working on it. I should be making a pull request by tomorrow.

**Comment by Devleena2003** [comment]
@IEdiong Have you finish your work? Or I will unassign you. The required time is already over.

**Comment by vaibhavi-roy** [comment]
Hello @soujo I would like to work on this issue

**Comment by IEdiong** [comment]
@soujo I'm done with this issue. 

I'll send in screenshots of what I've done so far. Sorry for the delay in responding.

**Comment by IEdiong** [comment]
![Screen Shot 2022-08-03 at 23 33 06](https://user-images.githubusercontent.com/81180771/182724203-4e9c093a-b7f5-4cc1-b0a6-68fd5eb228ff.png)
![Screen Shot 2022-08-03 at 23 33 24](https://user-images.githubusercontent.com/81180771/182724210-6833a682-caba-483e-be91-1a7ec0df771a.png)
![Screen Shot 2022-08-03 at 23 33 28](https://user-images.githubusercontent.com/81180771/182724217-86c51995-93e2-4265-b938-df6d1a392695.png)

**Comment by IEdiong** [comment]
Above are the desktop and mobile views. I await corrections and modifications before I make a pull request.

**Comment by Devleena2003** [comment]
Okay I'm reassigning you. Make a pull request
