### ISSUE TITLE
Leucos : Make hero section

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Leucos#2]
## Task 
- Make the hero section for the website

Reference : https://dribbble.com/shots/15752752-Chat-App-Landing-Page

Give the components a small floating animation

**Comment by Rajarshi12321** [comment]
I want to work on this issue, I would create the Hero Section close enough to the reference.

**Comment by Rajarshi12321** [comment]
Can I be assigned to this task?

**Comment by Devleena2003** [comment]
Yes I am assigning you, you can start working on this.

**Comment by Rajarshi12321** [comment]
I have made this hero section. 
Should I push it?

![image](https://user-images.githubusercontent.com/94736350/181204916-57ab5f70-aa23-49da-a864-cb7f1161149a.png)

**Comment by Devleena2003** [comment]
As mentioned in the task can you give some floating animation and box shadow in the icons?

**Comment by Rajarshi12321** [comment]
Actually its a whole image, giving box shadow and floating animation to the icons won't be possible, let me try other images

**Comment by Rajarshi12321** [comment]
would this work?

https://user-images.githubusercontent.com/94736350/181244226-de26f7cd-2487-4edc-b08f-bb236c1d39c8.mp4

**Comment by soujo** [comment]
> would this work?
> 
>  Hero.section.-.Personal.-.Microsoft.Edge.2022-07-27.17-44-10.mp4

The icons are scattered, it's not looking good and it's not even matching with the use of current website
Change the icons
Take help from the reference

**Comment by Rajarshi12321** [comment]
Can you please elaborate the part about scattered icons? cause they are floating as a whole svg.

**Comment by soujo** [comment]
The three icons have too much space between them , its not looking good. Make the UI better

**Comment by Rajarshi12321** [comment]
ok, I will resize them

**Comment by Rajarshi12321** [comment]
would this work?

https://user-images.githubusercontent.com/94736350/181435522-3b61bab7-1bda-4e48-a0c5-953ab1965147.mp4

**Comment by soujo** [comment]
> would this work?
> 
>  Hero.section.-.Personal.-.Microsoft.Edge.2022-07-28.11-52-40.mp4

Just by resizing, we can't get to that point 
Your first work was better than this because there should be meaning coming out of the hero section 
You can submit your first work .

**Comment by Rajarshi12321** [comment]
ok
