### ISSUE TITLE
Leucos : Redesign the Logo

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Leucos#3]
## Task 
- Redesign the logo for the website 
- Take reference from the internet 
- Don't make it too fancy

**Comment by SoumaBhuiya** [comment]
@soujo Hii , can I be assigned to this task ??

**Comment by Devleena2003** [comment]
Yes, you can start working.

**Comment by SoumaBhuiya** [comment]
![leucos 2](https://user-images.githubusercontent.com/98468590/181433442-2cf6af26-9010-4c42-ba13-44e95ec77755.png)


is it okk??

**Comment by soujo** [comment]
> ![leucos 2](https://user-images.githubusercontent.com/98468590/181433442-2cf6af26-9010-4c42-ba13-44e95ec77755.png)
> 
> is it okk??

We are designing the logo for the navbar and favicon, so make the logo according to that 
This logo is actually very good looking but there is no meaning of a chat app

**Comment by SoumaBhuiya** [comment]
![LOGO](https://user-images.githubusercontent.com/98468590/181603634-7a68ccf7-5f48-4dd1-955e-11f7cd17bbb1.png)


Now is it okk??

**Comment by SoumaBhuiya** [comment]
or should I change the black colour to white ??

**Comment by soujo** [comment]
> or should I change the black colour to white ??

yes its okay, you can raise a PR

**Comment by SoumaBhuiya** [comment]
okk Dada

**Comment by SoumaBhuiya** [comment]
Dada should I add this logo in the website and PR 
or just add the logo and then PR

**Comment by soujo** [comment]
> Dada should I add this logo in the website and PR or just add the logo and then PR

Add the png file in the `img` folder under static and name the file as `leucos-logo.png`

**Comment by SoumaBhuiya** [comment]
> > Dada should I add this logo in the website and PR or just add the logo and then PR
> 
> Add the png file in the `img` folder under static and name the file as `leucos-logo.png`

okk
