### ISSUE TITLE
Leucos : Design footer

### ISSUE THREAD

**Issue by soujo** [DSCKGEC/Leucos#5]
## Task 
- Design the footer for the website 
- Make the footer in `views/partials/footer.html` and `static/css/partials/footer.css`
- Take reference from the internet 
- Don't make it too big

**Comment by RajavJain** [comment]
Hello, can I Start working on it?

**Comment by soujo** [comment]
> Hello, can I Start working on it?

Yes sure, assigned to you

**Comment by RajavJain** [comment]
<img width="1440" alt="Screenshot 2022-07-31 at 02 18 16" src="https://user-images.githubusercontent.com/98579217/182037144-b89c94b2-a885-4d57-8655-4d93ec64167c.png">
Will it work?

**Comment by Devleena2003** [comment]
Your work is completely fine!! But you made changes in the index.ejs file. You have to make changes in footer.ejs and footer.css files only. Don't change the other files.

**Comment by RajavJain** [comment]
Ok sure I will be creating a new PR.
