### ISSUE TITLE
Design the Title

### ISSUE THREAD

**Issue by Devleena2003** [DSCKGEC/Leucos#6]
## Task

- Design the website title 'Leucos'
- Make it animated like this title : https://dscksoc.herokuapp.com/
or,
- You can make it like this : https://dribbble.com/shots/15752752-Chat-App-Landing-Page

**Comment by marekbrown** [comment]
Hi, can I be assigned to this task?

**Comment by marekbrown** [comment]
Hi, can I be assigned to this task? @Devleena2003 @soujo 

Also, do you think the text would look best in white? or should I use colours that match the rest of the site, something like this:

![ShareX_brave_26-07-2022_16-35-09](https://user-images.githubusercontent.com/44444111/181049386-68826eae-b919-44d9-a623-c28873a1741a.gif)

**Comment by Devleena2003** [comment]
Yes that would be fine, you can start work.

**Comment by Devleena2003** [comment]
@marekbrown In PR template you have to mark in KSOC participant as this event is under KGEC Summer Of Code.

**Comment by marekbrown** [comment]
@Devleena2003 done
